pipeline {
    agent any
    environment {
        AWS_ACCOUNT_ID="609245952838"
        AWS_DEFAULT_REGION="us-east-2" 
        IMAGE_REPO_NAME="jenkins-ecr-repo"
        BUILD_COUNTER = sh(script: 'echo $((BUILD_NUMBER - 1))', returnStdout: true).trim()
        IMAGE_TAG="latest${BUILD_COUNTER}"
        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}"
    }
    
    stages {
        stage('Logging into AWS ECR') {
            steps {
                script {
                    sh "aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
                }
            }
        }

        stage('Cloning Git') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/md-zubair/Docker-sample.git']]) 
            }
        }

        stage('Building Maven package') {
            steps {
                dir('/var/lib/jenkins/workspace/ECS-demo/complete/') { 
                    script {
                        sh 'mvn clean package'
                    }
                }
            }
        }
 
        stage('Building image') {
            steps {
                script {
                    dockerImage = docker.build "${IMAGE_REPO_NAME}:${IMAGE_TAG}"
                }
            }
        }

        stage('Pushing to ECR') {
            steps { 
                script {
                    sh "docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}:${IMAGE_TAG}"
                    sh "docker push ${REPOSITORY_URI}:${IMAGE_TAG}"
                }
            }
        }
    }
}
